site_name: CSC-palvelut Haaga-Heliassa
nav:
  - Aloitus: index.md
  - Opiskelijan aloitusohjeet: aloitus_opiskelija.md
  - reseptit/spring_rahti.md
  - reseptit/react_rahti.md
  - Rahti-ohjeita:
    - Yleisiä ohjeita: 
      - rahti/projektin_luonti.md
      - rahti/buildin_automatisointi.md
      - rahti/virheenjaljitys.md 
      - rahti/julkaisu_yksityisesta_repositoriosta.md
      - rahti/komentorivityokalun_asennus.md
    - Spring Boot -ohjeita: 
      - rahti/spring_ilman_tietokantaa.md
      - rahti/spring_rahti_pukki.md
    - React-ohjeita:
      - rahti/react_julkaiseminen.md
theme: 
  name: material
  language: fi
  features:
    - content.code.copy
    - toc.follow
    - navigation.top

  favicon: assets/favicon-192x192.png
  logo: assets/haaga-helia.png
extra_css:
  - stylesheets/extra.css
plugins:
    - search
    - mermaid2
    - open-in-new-tab:
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
