site_name: CSC-palvelut Haaga-Heliassa
nav:
  - Aloitus: index.md
  - opettajan_ohje.md
  - opiskelijan_ohje.md
  - Reseptit:
    - reseptit/spring_rahti.md
    - reseptit/react_rahti.md
  - Rahti:
    - Yleiset ohjeet: 
      - rahti/projektin_luonti.md
      - rahti/komentorivityokalun_asennus.md
      - rahti/tietokantapalvelun_luominen.md
      - rahti/https_konfigurointi.md
      - rahti/buildin_automatisointi.md
      - rahti/julkaisu_yksityisesta_repositoriosta.md
      - rahti/virheenjaljitys.md 
    - Spring Boot -ohjeet: 
      - rahti/spring_ilman_tietokantaa.md
      - rahti/spring_tietokannan_konfigurointi.md
      - rahti/spring_jkube_plugin.md
    - React-ohjeet:
      - rahti/react_julkaiseminen.md
theme: 
  name: material
  language: fi
  features:
    - content.code.copy
    - toc.follow
    - navigation.top

  favicon: assets/favicon-192x192.png
  logo: assets/haaga-helia.png
extra_css:
  - stylesheets/extra.css
plugins:
    - search
    - mermaid2
    - open-in-new-tab:
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
